import { AdmissionCase } from './types';

export const SEED_ADMISSION_CASES: AdmissionCase[] = [
  {
    id: "1",
    year: 2024,
    grade: 5.18,
    location: "경상남도",
    universityName: "가야대학교",
    admissionType: "학생부교과",
    detailedType: "인문계고출신자",
    departmentName: "간호학과",
    step1Result: "해당없음",
    finalResult: "불합격",
    failReason: "",
    waitlistRank: "",
    waitlistHistory: "",
    isEnrolled: "-"
  },
  {
    id: "2",
    year: 2024,
    grade: 5.78,
    location: "경상남도",
    universityName: "가야대학교",
    admissionType: "학생부교과",
    detailedType: "일반학생",
    departmentName: "간호학과",
    step1Result: "해당없음",
    finalResult: "불합격",
    failReason: "",
    waitlistRank: "47",
    waitlistHistory: "47",
    isEnrolled: "-"
  },
  {
    id: "3",
    year: 2024,
    grade: 5.85,
    location: "경상남도",
    universityName: "가야대학교",
    admissionType: "학생부교과",
    detailedType: "인문계고출신자",
    departmentName: "간호학과",
    step1Result: "해당없음",
    finalResult: "충원합격",
    failReason: "",
    waitlistRank: "200",
    waitlistHistory: "200",
    isEnrolled: "N"
  },
  {
    id: "4",
    year: 2024,
    grade: 2.52,
    location: "경기도",
    universityName: "가천대학교",
    admissionType: "학생부교과",
    detailedType: "학생부우수자",
    departmentName: "생명과학과",
    step1Result: "해당없음",
    finalResult: "충원합격",
    failReason: "",
    waitlistRank: "7",
    waitlistHistory: "7-0",
    isEnrolled: "Y"
  },
  {
    id: "5",
    year: 2024,
    grade: 2.83,
    location: "경기도",
    universityName: "가천대학교",
    admissionType: "학생부교과",
    detailedType: "학생부우수자",
    departmentName: "바이오나노학과",
    step1Result: "해당없음",
    finalResult: "불합격",
    failReason: "최저미충족",
    waitlistRank: "",
    waitlistHistory: "",
    isEnrolled: "-"
  },
  {
    id: "6",
    year: 2024,
    grade: 2.83,
    location: "경기도",
    universityName: "가천대학교",
    admissionType: "학생부교과",
    detailedType: "지역균형",
    departmentName: "생명과학과",
    step1Result: "합격",
    finalResult: "불합격",
    failReason: "",
    waitlistRank: "9",
    waitlistHistory: "9",
    isEnrolled: "-"
  },
  {
    id: "7",
    year: 2024,
    grade: 2.93,
    location: "경기도",
    universityName: "가천대학교",
    admissionType: "학생부교과",
    detailedType: "학생부우수자",
    departmentName: "기계공학전공",
    step1Result: "해당없음",
    finalResult: "충원합격",
    failReason: "",
    waitlistRank: "19",
    waitlistHistory: "19-0",
    isEnrolled: "N"
  },
  {
    id: "8",
    year: 2024,
    grade: 3.12,
    location: "경기도",
    universityName: "가천대학교",
    admissionType: "학생부교과",
    detailedType: "학생부우수자",
    departmentName: "건축학부",
    step1Result: "해당없음",
    finalResult: "불합격",
    failReason: "최저미충족",
    waitlistRank: "",
    waitlistHistory: "",
    isEnrolled: "-"
  },
  {
    id: "9",
    year: 2024,
    grade: 3.22,
    location: "경기도",
    universityName: "가천대학교",
    admissionType: "학생부교과",
    detailedType: "학생부우수자",
    departmentName: "유아교육학과",
    step1Result: "해당없음",
    finalResult: "충원합격",
    failReason: "",
    waitlistRank: "8",
    waitlistHistory: "8-5-2-0",
    isEnrolled: "N"
  },
  {
    id: "10",
    year: 2024,
    grade: 3.32,
    location: "경기도",
    universityName: "가천대학교",
    admissionType: "학생부종합",
    detailedType: "가천바람개비",
    departmentName: "생명과학과",
    step1Result: "불합격",
    finalResult: "불합격",
    failReason: "",
    waitlistRank: "",
    waitlistHistory: "",
    isEnrolled: "-"
  },
  {
    id: "100",
    year: 2024,
    grade: 2.32,
    location: "서울특별시",
    universityName: "경희대학교",
    admissionType: "학생부종합",
    detailedType: "네오르네상스",
    departmentName: "미디어학과",
    step1Result: "불합격",
    finalResult: "불합격",
    failReason: "",
    waitlistRank: "",
    waitlistHistory: "",
    isEnrolled: "-"
  },
  {
    id: "101",
    year: 2024,
    grade: 1.0,
    location: "서울특별시",
    universityName: "홍익대학교",
    admissionType: "학생부종합",
    detailedType: "학교생활우수자",
    departmentName: "심리학과",
    step1Result: "합격",
    finalResult: "합격",
    failReason: "",
    waitlistRank: "",
    waitlistHistory: "",
    isEnrolled: "Y"
  }
];
